### ISSUE TITLE
'ConfigEntries' object has no attribute 'async_setup_platforms'

### ISSUE THREAD

**Issue by sanvrb** [RenierM26/ha-ezviz#67]
I migrated from legacy setup to new setup.
However, the integration seems to be broken on my HA instance.

I made sure the old config was completely removed. I also reinstalled the add-on via the integrations tab.

This is the error I am getting:

```
Logger: homeassistant.config_entries
Source: custom_components/ezviz_cloud/__init__.py:86
First occurred: 9:08:18 AM (1 occurrences)
Last logged: 9:08:18 AM

Error setting up entry (username)+ezviz@gmail.com for ezviz_cloud
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 249, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/ezviz_cloud/__init__.py", line 86, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

**Comment by RenierM26** [comment]
Hi @sanvrb,

Are you using the latest HA release? Or an older one?

**Comment by sanvrb** [comment]
hi @RenierM26, I am currently stuck on HA core-2021.4.6. HA-EZVIZ is v.0.0.6.3.

**Comment by sanvrb** [comment]
Currently reverted back to HA-EZVIZ 0.0.6.2 and all works well on HA 2021.4.6

**Comment by RenierM26** [comment]
Hi @sanvrb,

Just our of curiosity, why are you stuck on an older version of Hass?

**Comment by sanvrb** [comment]
@RenierM26 Main reason was issues with other add-ons need for daily use. I patch was released meanwhile for these add-ons and I updated to HA 2021.5.5. HA-EZVIZ 0.0.6.3 works as expected on this release.

**Comment by RenierM26** [comment]
Thank you for the feedback @sanvrb
